name: Deploy Firebase Hosting

on:
  push:
    branches: [ github-actions ]

jobs:
  firebase_deploy:
    name: Deploy app to firebase hosting to update custom domain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm i -g typescript && tsc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NBA_TRACKER_APP }}'
          channelId: live
          projectId: nba-tracker-app